### ISSUE TITLE
Lots of small nitpicky issues

### ISSUE THREAD

**Issue by ddm999** [HackSoc/hacksoc.org#64]
- [ ] the description for Movie Nights implies there's always 2 films (there rarely is)
- [x] the website icon is oppositely coloured to the actual logo (unless this is supposed to be a thing)
- [x] the calendar says "Activites"
- [x] there's a random combination of ; and . at the end of the guidelines on irc.html
- [x] the navigation bar should probably either have proper capitalisation or not: a mixture of both looks weird ("github", "facebook" and "Slack/IRC chat")
- [x] there's a few places where Slack is written "slack"

**Comment by danieljabailey** [comment]
Some meta-nitpicks...
>  the calendar says "Activites"

So?
> the website icon is oppositely coloured to the actual logo (unless this is supposed to be a thing)

What is our reference for "the actual logo"?
> the description for Movie Nights implies there's always 2 films (there rarely is)

Fair
> there's a random combination of ; and . at the end of the guidelines on irc.html

True.
> the navigation bar should probably either have proper capitalisation or not: a mixture of both looks weird ("github", "facebook" and "Slack/IRC chat")
> there's a few places where Slack is written "slack"

Also fair, you should probably PR for the trivial fixes.

**Comment by LukeMoll** [comment]
> the navigation bar should probably either have proper capitalisation or not: a mixture of both looks weird ("github", "facebook" and "Slack/IRC chat")

This is fixed in #65 - navbar is completely lowercase. If that isn't merged then that can be fixed seperately.

And some meta-meta (or meta²) nitpicks...
> >the calendar says "Activites"  
>
> So?

It's a typo, that's not how you spell Activities

> > the website icon is oppositely coloured to the actual logo (unless this is supposed to be a thing)
>
>What is our reference for "the actual logo"?

I would understand that to mean [logo2017.svg](https://github.com/HackSoc/hacksoc.org/blob/master/static/logo2017.svg), the logo that appears centrally on the website and all social media. Admittedly this is not reflected in [visual-identity](https://github.com/hacksoc/visual-identity), but that's more a problem with that repository than this issue.

**Comment by danieljabailey** [comment]
Okay, time to complete the meta-cube...
>>> the calendar says "Activites"
>>
>>So?
>
>It's a typo, that's not how you spell Activities

Dan, you could have mentioned that the problem was the spelling :P 

>>> the website icon is oppositely coloured to the actual logo (unless this is supposed to be a thing)
>>>
>>What is our reference for "the actual logo"?
>>
>I would understand that to mean logo2017.svg, the logo that appears centrally on the website and all social media. Admittedly this is not reflected in visual-identity, but that's more a problem with that repository than this issue.

Dan, you could have mentioned that it was the favicon that didn't match the logo on the page. :P 
I don't care enough about the favicon TBH, but yeah maybe someone should fix that.

**Comment by LordAro** [comment]
You guys suck at both making bug reports and replying to them, just in case
you were unaware :)

**Comment by danieljabailey** [comment]
@LordAro you suck at being tactful, just in case you were unaware :P

**Comment by LukeMoll** [comment]
Fixed most of this in [39a999d](https://github.com/HackSoc/hacksoc.org/commit/39a999d9a4b4d70a9dc4d211e529550ba9b5743f):

 - Chosen to use all-lowercase for the navbar
 - Otherwise Slack is capitalised.

**Comment by LukeMoll** [comment]
Website icon fixed in [00686ce].(https://github.com/HackSoc/hacksoc.org/commit/00686ceafa7f8800ec692352da840c49079f028f)
